accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

cookie_stands/urls.py
from django.urls import path
from .views import CookieStandList, CookieStandDetail

urlpatterns = [
    path("", CookieStandList.as_view(), name="cookie_stand_list"),
    path("<int:pk>/", CookieStandDetail.as_view(), name="cookie_stand_detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views
from .views import MyTokenObtainPairView
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/cookie_stands/", include("cookie_stands.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "api/token/",
        MyTokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    path(
        "api/token/refresh/",
        jwt_views.TokenRefreshView.as_view(),
        name="token_refresh",
    ),
    path("cookie_stands/", include("cookie_stands.urls_front")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username

cookie_stands/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

class CookieStand(models.Model):
    name = models.CharField(max_length=256)
    location = models.CharField(max_length=256, default='')
    rating = models.IntegerField(default=0, blank=True)
    reviewer = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, null=True, blank=True
    )
    owner = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, null=True, blank=True, related_name='cookie_stands'
    )
    description = models.TextField(default="", null=True, blank=True)
    hourly_sales = models.JSONField(default=list, null=True)
    minimum_customers_per_hour = models.IntegerField(default=0)
    maximum_customers_per_hour = models.IntegerField(default=0)
    average_cookies_per_sale = models.FloatField(default=0)

    def __str__(self):
        return self.location

    def get_absolute_url(self):
        return reverse('cookie_stand_detail', args=[str(self.id)])

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

cookie_stands/views.py
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)
from .models import CookieStand
from .permissions import IsOwnerOrReadOnly
from .serializers import CookieStandSerializer


class CookieStandList(ListCreateAPIView):
    queryset = CookieStand.objects.all()
    serializer_class = CookieStandSerializer


class CookieStandDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsOwnerOrReadOnly,)
    queryset = CookieStand.objects.all()
    serializer_class = CookieStandSerializer

project/views.py
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView


class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)

        # Add custom claims
        token["email"] = user.email
        token["username"] = user.username
        # ...

        return token


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="w-3/4 mx-auto max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="flex justify-end px-4 pt-4">
        <button id="dropdownButton" data-dropdown-toggle="dropdown" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
            <span class="sr-only">Open dropdown</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"></path></svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdown" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
            <ul class="py-2" aria-labelledby="dropdownButton">
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Edit</a>
            </li>
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Export Data</a>
            </li>
            <li>
                <a href="#" class="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Delete</a>
            </li>
            </ul>
        </div>
    </div>
    <div class="flex flex-col items-center pb-10 px-4">
        <img class="w-96 h-96 mb-3 rounded-full shadow-lg" src="https://placekeanu.com/200/150" alt="Keanu image"/>
        <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">Not Keanu Reeves</h5>
        <span class="text-sm text-gray-500 dark:text-gray-400">Full Stack Developer</span>
        <div class="flex mt-4 space-x-3 md:mt-6">
            <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add friend</a>
            <a href="#" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-gray-900 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-700 dark:focus:ring-gray-700">Message</a>
        </div>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}All the CookieStands{% endblock %}</title>
 <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-green-50">
<header>
  <nav class="bg-gray-900 border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
        <div class="container flex flex-wrap items-center justify-between mx-auto">
          <a href="{% url 'home' %}">
              <img src="https://upload.wikimedia.org/wikipedia/commons/7/78/CookieStands_Logo.svg" class="p-3 h-12 bg-white rounded" alt="Logo" />
          </a>
          <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
            <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
            {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}" class="block py-2 pl-3 pr-4 text-white bg-green-700 rounded md:bg-transparent  md:p-0 dark:text-white" aria-current="page">Log Out</a>
              </li>
              {% else %}
              <li>
                <a href="{% url 'login' %}" class="block py-2 pl-3 pr-4 text-white bg-green-700 rounded md:bg-transparent  md:p-0 dark:text-white" aria-current="page">Log In</a>
              </li>
            {% endif %}

              <li>
                <a href="{% url 'about' %}" class="block py-2 pl-3 pr-4 text-white border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
              </li>
              {% if request.user.is_authenticated %}
                <li>
                <a href="{% url 'cookie_stand_list' %}" class="block py-2 pl-3 pr-4 text-white border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">List</a>
                </li>
                 <li>
                <a href="{% url 'cookie_stand_create' %}" class="block py-2 pl-3 pr-4 text-white border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Create</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
</header>
<main>
<div class="container mx-auto mt-4">
  {% block content %}
  {% endblock content %}
</div>
</main>
<footer
      class="bg-gray-900
             text-sm text-white
             fixed
             inset-x-0
             bottom-0
             p-2">
      &copy; CodeFellows 2023
    </footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>
</body>
</html>

templates/cookie_stand/cookie_stand_create.html
{% extends 'base.html' %}

{% block content %}


  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Create a CookieStand</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">CookieStand Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               placeholder="e.g. celery" required>

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">CookieStand Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="0" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}">{{  choice }}</option>
          {% endfor %}
        </select>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Create
      </button>

    </form>
  </div>

{% endblock content %}

templates/cookie_stand/cookie_stand_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete CookieStand</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ cookie_stand.name }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/cookie_stand/cookie_stand_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="space-y-8 p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">

  <div class="flex">

    <h5 class=" flex-auto mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ cookie_stand.name }}</h5>


    <a href="{% url 'cookie_stand_update' cookie_stand.pk %}">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-blue-600">
        <path
          d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-8.4 8.4a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32l8.4-8.4z" />
        <path
          d="M5.25 5.25a3 3 0 00-3 3v10.5a3 3 0 003 3h10.5a3 3 0 003-3V13.5a.75.75 0 00-1.5 0v5.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5V8.25a1.5 1.5 0 011.5-1.5h5.25a.75.75 0 000-1.5H5.25z" />
      </svg>

    </a>

    <a href="{% url 'cookie_stand_delete' cookie_stand.pk %}">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 text-red-600">
        <path fill-rule="evenodd"
          d="M16.5 4.478v.227a48.816 48.816 0 013.878.512.75.75 0 11-.256 1.478l-.209-.035-1.005 13.07a3 3 0 01-2.991 2.77H8.084a3 3 0 01-2.991-2.77L4.087 6.66l-.209.035a.75.75 0 01-.256-1.478A48.567 48.567 0 017.5 4.705v-.227c0-1.564 1.213-2.9 2.816-2.951a52.662 52.662 0 013.369 0c1.603.051 2.815 1.387 2.815 2.951zm-6.136-1.452a51.196 51.196 0 013.273 0C14.39 3.05 15 3.684 15 4.478v.113a49.488 49.488 0 00-6 0v-.113c0-.794.609-1.428 1.364-1.452zm-.355 5.945a.75.75 0 10-1.5.058l.347 9a.75.75 0 101.499-.058l-.346-9zm5.48.058a.75.75 0 10-1.498-.058l-.347 9a.75.75 0 001.5.058l.345-9z"
          clip-rule="evenodd" />
      </svg>
    </a>

  </div>

  <h5 class=" flex-auto mb-2 text-md font-bold tracking-tight text-gray-900 dark:text-white">Reviewed by: {{
    cookie_stand.reviewer }}</h5>


  <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{ cookie_stand.description }}</p>


  <div class="flex items-center">

    {% for i in "12345" %}

    <svg aria-hidden="true"
      class="w-5 h-5  {% if i > cookie_stand.rating|slugify %}text-grey-300{% else %}text-yellow-400{% endif %}"
      fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
      <title>First star</title>
      <path
        d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z">
      </path>
    </svg>
    {% endfor %}

  </div>


  <a href="https://en.wikipedia.org/wiki/{{ cookie_stand.name }}"
    class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
    Read more
    <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd"
        d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
        clip-rule="evenodd"></path>
    </svg>
  </a>
</div>



{% endblock content %}

templates/cookie_stand/cookie_stand_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update CookieStand</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a CookieStand</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ cookie_stand.name }}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ cookie_stand.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}" {% if value == cookie_stand.reviewer.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ cookie_stand.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}

templates/things/thing_create.html
{% extends 'base.html' %}

{% block content %}


  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Create a CookieStand</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">CookieStand Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               placeholder="e.g. celery" required>

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">CookieStand Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="0" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}">{{  choice }}</option>
          {% endfor %}
        </select>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Create
      </button>

    </form>
  </div>

{% endblock content %}

templates/things/thing_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete CookieStand</h1>
  <form method="POST">
  {% csrf_token %}
    <p>Do you really want to delete "{{ cookie_stand.name }}"?</p>
    <input type="submit" value="OK">
  </form>
{% endblock content %}

templates/things/thing_update.html
{% extends 'base.html' %}

{% block content %}
  {#  <h1>Update CookieStand</h1>#}
  {#  <form method="POST">#}
  {##}
  {#    {{ form.as_p }}#}
  {#    <input type="submit" value="SAVE">#}
  {#  </form>#}

  <div
    class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-6" method="POST">
      {% csrf_token %}
      <h5 class="text-xl font-medium text-gray-900 dark:text-white">Update a CookieStand</h5>
      <div>
        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
        <input type="text" name="name" id="id_name"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               required value="{{ cookie_stand.name }}">

      </div>
      <div>
        <label for="id_rating" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Rating</label>
        <input type="number" name="rating" id="id_rating"
               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
               value="{{ cookie_stand.rating }}" min="0" max="5" required>
      </div>
      <div>
        <label for="id_reviewer" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Reviewer</label>
        <select name="reviewer" id="id_reviewer">
          {% for value, choice in form.fields.reviewer.choices %}
            <option value="{{ value }}" {% if value == cookie_stand.reviewer.id %}selected{% endif %}>{{ choice }}</option>
          {% endfor %}
        </select>
      </div>

      <div>
        <label for="id_description"
               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description</label>
        <textarea name="description" id="id_description"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                  placeholder="e.g. Celery gets a bad wrap" required>{{ cookie_stand.description }}</textarea>
      </div>


      <button type="submit"
              class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        SAVE
      </button>

    </form>
  </div>
{% endblock content %}